---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo
  namespace: dev
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:dev-*
spec:
  releaseName: echo-dev
  chart:
    git: git@github.com:JakobLarchik/helm-operator-get-started
    path: charts/echoChart
    ref: master
  values:
    app:
      replicaCount: 2
      container:
        image: gcr.io/arcane-sentinel-320611/echo 
        tag: latest