---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo
  namespace: prod
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: semver:~0.4
spec:
  releaseName: echo-prod
  chart:
    git: git@github.com:JakobLarchik/helm-operator-get-started
    path: charts/echoChart
    ref: master
  values:
    image:
      repository: gcr.io/arcane-sentinel-320611/echo
      tag: 0.4.11
    replicaCount: 3
