---
apiVersion: helm.fluxcd.io/v1
kind: HelmRelease
metadata:
  name: echo-rc
  namespace: stg
  annotations:
    fluxcd.io/automated: "true"
    filter.fluxcd.io/chart-image: glob:stg-*
spec:
  releaseName: echo-rc
  chart:
    git: git@github.com:JakobLarchik/helm-operator-get-started
    path: charts/echoChart
    ref: master
  values:
    image:
      repository: gcr.io/arcane-sentinel-320611/echo
      tag: stg-9ij63o4c
    replicaCount: 2
    hpa:
      enabled: true
      maxReplicas: 10
      cpu: 50
      memory: 256Mi
